package src.seeding;

import src.controller.CustomerController;
import src.controller.Payment_methodController;
import src.controller.SubscribeController;
import src.controller.SubscriptionController;
import src.model.Subscription;
import src.model.Customer;
import src.model.Payment_method;
import src.model.Subscribe;
import java.util.Date;

public class SubscribeSeeding {

    public static void seed() {
        SubscribeController subscribectrl = new SubscribeController();
        CustomerController custctrl = new CustomerController();
        SubscriptionController subctrl = new SubscriptionController();
        Payment_methodController payctrl = new Payment_methodController();
        Integer i;

        i = 1;
        Customer c1 = custctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Subscription s1 = subctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Payment_method p1 = payctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Date d1 = new Date(2002, 02, 21);
        Subscribe t1 = new Subscribe(c1, s1, d1, p1, "none");
        subscribectrl.addSubscribe(t1);
        i = 1;
        Customer c2 = custctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Subscription s2= subctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Payment_method p2 = payctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Date d2 = new Date(2022, 01, 02);
        Subscribe t2 = new Subscribe(c2, s2, d2, p2, "none");
        subscribectrl.addSubscribe(t2);
        i = 3;
        Customer c3 = custctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Subscription s3 = subctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Payment_method p3 = payctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Date d3 = new Date(2002, 02, 23);
        Subscribe t3 = new Subscribe(c3, s3, d3, p3, "none");
        subscribectrl.addSubscribe(t3);
        i = 4;
        Customer c4= custctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Subscription s4= subctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Payment_method p4 = payctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Date d4 = new Date(2012, 05, 16);
        Subscribe t4 = new Subscribe(c4, s4, d4, p4, "none");
        subscribectrl.addSubscribe(t4);
        i = 5;
        Customer c5 = custctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Subscription s5 = subctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Payment_method p5 = payctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Date d5 = new Date(2022, 03, 11);
        Subscribe t5 = new Subscribe(c5, s5, d5, p5, "none");
        subscribectrl.addSubscribe(t5);
        i = 6;
        Customer c6 = custctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Subscription s6 = subctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Payment_method p6 = payctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Date d6 = new Date(2017, 02, 21);
        Subscribe t6 = new Subscribe(c6, s6, d6, p6, "none");
        subscribectrl.addSubscribe(t6);
        i = 7;
        Customer c7 = custctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Subscription s7 = subctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Payment_method p7 = payctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Date d7 = new Date(2018, 07, 21);
        Subscribe t7 = new Subscribe(c7, s7, d7, p7, "none");
        subscribectrl.addSubscribe(t7);
        i = 8;
        Customer c8 = custctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Subscription s8 = subctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Payment_method p8 = payctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Date d8 = new Date(2016, 12, 30);
        Subscribe t8 = new Subscribe(c8, s8, d8, p8, "none");
        subscribectrl.addSubscribe(t8);
        i = 9;
        Customer c9 = custctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Subscription s9 = subctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Payment_method p9 = payctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Date d9 = new Date(2002, 05, 01);
        Subscribe t9 = new Subscribe(c9, s9, d9, p9, "none");
        subscribectrl.addSubscribe(t9);
        i = 10;
        Customer c10 = custctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Subscription s10 = subctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Payment_method p10 = payctrl.getValueByIndex(Long.valueOf(i.longValue()));
        Date d10 = new Date(2002, 02, 13);
        Subscribe t10 = new Subscribe(c10, s10, d10, p10, "none");
        subscribectrl.addSubscribe(t1);
    };
}
